package:
    name:           omnipay-epayments
    namespace:      Omnipay\ePayments
    headline:       Omnipay: ePayments
    title:          ePayments driver for Omnipay payment processing library
    type:           library
    license:        MIT
    keywords:       php, omnipay, epayments, merchant, payment
    description:    |
        [Omnipay](https://github.com/omnipay/omnipay) is a framework agnostic, multi-gateway payment
        processing library for PHP 5.3+.
        This package implements [ePayments](https://epayments.com/) support for Omnipay.

require:
    hiqdev/hidev-config:        "*"
    hiqdev/hidev-config-php:    "*"
